---
title: "Q1Avery"
author: "Avery Kan"
date: "April 14, 2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
q1 <- read.csv("q1_train.csv")
q1 <- ts(q1[,2])

#1.Exploratory data analysis
plot(q1)
```

```{r}
#2.Transform data: variance stabilization
#increasing variance indicates that log transformation is necessary
q1 = q1 + abs(min(q1))
q1.ln = log(q1)
plot(q1.ln)
q1.sq = sqrt(q1)
plot(q1.sq)
q1.sqd <- diff(q1.sq)
acf(q1.sqd,500)
#square is absolutely better
```

```{r}
#3.Remove mean structure (parametric model, smoothing, differencing)
#figure out a slightly increasing trend, try linear model, quadratic model and polynomial
t1 = 1:length(q1.sq)
t2 = t1^2
t3 = t1^3
q1.m1 = lm(q1.sq ~ t1)
q1.m1
q1.m2 = lm(q1.sq ~ t1 + t2)
q1.m2
q1.m3 = lm(q1.sq ~ t1 + I(t2) + I(t3))
q1.m3
summary(q1.m1)
summary(q1.m2)
summary(q1.m3)
q1.m1.r = q1 - q1.m1$fitted.values
plot(q1.m1.r)
plot(q1.sq)
points(q1.m3$fitted.values)
q1.m2.r = q1 - q1.m2$fitted.values
plot(q1.m2.r)
q1.m3.r = q1 - q1.m3$fitted.values
plot(q1.m3.r)
#no big difference, not helping
```

```{r}
#fit a sinusoid
t = 1: length(q1.sq)
f1 = 1
f2 = 2
f3 = 3
d = 52
v1 = cos(2*pi*f1*t/d)
v2 = sin(2*pi*f1*t/d)
v3 = cos(2*pi*f2*t/d)
v4 = sin(2*pi*f2*t/d)
v5 = cos(2*pi*f3*t/d)
v6 = sin(2*pi*f3*t/d)
q1.si = lm(q1.m3.r ~ v1 + v2 + v3 + v4 +v5 + v6)
plot(t, q1.si$residuals)
plot(q1.m3.r)
points(t, q1.si$fitted.values, type = "l", col = "red")
q1.m3.r2 <- q1.m3.r-q1.si$fitted.values
plot(diff(q1.m3.r2))
pacf(diff(q1.m3.r2), 10)
pacf(diff(q1.m3.r2), 500)



```

```{r}
#4.Fit ARMA model to residuals.

```

```{r}
#5.Check if model fit is good. (Diagnostics)
```

```{r}
#6.Forecast
```

